collections:
  courses:
    output: true



defaults:
  - scope:
      path: "_courses/programmeren"
    values:
      course: "programmeren"
      layout: "programmeren"
  - scope:
      path: "_courses/webontwikkeling"
    values:
      course: "webontwikkeling"
      layout: "course"
  - scope:
      path: "_courses/databanken"
    values:
      course: "databanken"
      layout: "course"
  - scope:
      path: ""
    values:
      layout: "default"