collections:
  courses:
    output: true



defaults:
  - scope:
      type: "courses"
    values:
      layout: "course"
  - scope:
      type: "courses"
    values:
      layout: "course"
#      permalink: /:collection/:title:output_ext
  - scope:
      path: ""
    values:
      layout: "default"